[workspace]
authors = ["sapetnioc <sapetnioc@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "cati_fs"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
libfuse = ">=3.10.4,<4"
sqlite = ">=3.51.1,<4"
pkg-config = ">=0.29.2,<0.30"
make = ">=4.4.1,<5"
python = ">=3.14.2,<3.15"
